version: "1"
services:
  - type: web
    name: newsmonitor-pro
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 5000
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: newsmonitor-disk
      size: 3GB
      mount: /app/db
